# Generated by Django 6.0.8 on 2026-09-12 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallets.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ledger_entry_amount_nonzero')],
            },
        ),
    ]
