# Generated by Django 6.0.8 on 2026-09-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["wallet", "-created_at", "-id"], name="ledger_entry_wallet_recent_idx"
            ),
        ),
    ]
