# Generated by Django 6.0.8 on 2026-09-25 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_ledgerentry_ledger_entry_wallet_recent_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("wallets_checked", models.PositiveIntegerField(default=0)),
                ("transactions_checked", models.PositiveIntegerField(default=0)),
                ("wallet_mismatches", models.PositiveIntegerField(default=0)),
                ("unbalanced_transactions", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
